// <auto-generated />
using System;
using EcommerceBackend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250707182225_fixingtables")]
    partial class fixingtables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.BookModels.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.BookModels.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PublishedAt")
                        .HasColumnType("date");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TypeId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.BookModels.BookCopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId")
                        .IsUnique();

                    b.ToTable("BooksCopies");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.BookModels.BookType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BooksTypes");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.CartModels.CartItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ProductId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ClientModels.Client", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.HasKey("PersonId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ClientModels.ClientAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TokenId");

                    b.ToTable("ClientsAccounts");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ClientXEmployeeModels.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(22)
                        .HasColumnType("nvarchar(22)");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ClientXEmployeeModels.Token", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientPersonId")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientPersonId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.EmployeeModels.Employee", b =>
                {
                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.HasKey("PersonId");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.EmployeeModels.EmployeeAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TokenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountTypeId");

                    b.HasIndex("TokenId")
                        .IsUnique();

                    b.ToTable("EmployeeAccount");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.EmployeeModels.EmployeeAccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeAccountTypes");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.OrderModels.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ArrivedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ShipmentAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int>("TotalQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.OrderModels.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.Colors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("ProductColors");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<float>("InitialPrice")
                        .HasColumnType("real");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("MainImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.ProductMainImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductMainImages");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.ProductXColorsXSizes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("ProductXSizesId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductXSizesId");

                    b.ToTable("ProductsXColorsXSizes");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.ProductXColorsXSizesImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductXColorsXSizesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductXColorsXSizesId");

                    b.ToTable("ProductXColorsXSizesImages");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.ProductXSizes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.ToTable("ProductXSizes");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.Sizes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductSizes");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.Types", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.BookModels.Book", b =>
                {
                    b.HasOne("EcommerceBackend.Core.Domain.Models.BookModels.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceBackend.Core.Domain.Models.BookModels.BookType", "BookType")
                        .WithMany("Books")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("BookType");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.BookModels.BookCopy", b =>
                {
                    b.HasOne("EcommerceBackend.Core.Domain.Models.BookModels.Book", "Book")
                        .WithOne("BookCopies")
                        .HasForeignKey("EcommerceBackend.Core.Domain.Models.BookModels.BookCopy", "BookId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.CartModels.CartItems", b =>
                {
                    b.HasOne("EcommerceBackend.Core.Domain.Models.ClientModels.Client", "client")
                        .WithMany("Carts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceBackend.Core.Domain.Models.ProductModels.Product", "product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("client");

                    b.Navigation("product");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ClientModels.Client", b =>
                {
                    b.HasOne("EcommerceBackend.Core.Domain.Models.ClientModels.ClientAccount", "Account")
                        .WithOne("Client")
                        .HasForeignKey("EcommerceBackend.Core.Domain.Models.ClientModels.Client", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcommerceBackend.Core.Domain.Models.ClientXEmployeeModels.Person", "Person")
                        .WithOne("Client")
                        .HasForeignKey("EcommerceBackend.Core.Domain.Models.ClientModels.Client", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ClientModels.ClientAccount", b =>
                {
                    b.HasOne("EcommerceBackend.Core.Domain.Models.ClientXEmployeeModels.Token", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Token");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ClientXEmployeeModels.Token", b =>
                {
                    b.HasOne("EcommerceBackend.Core.Domain.Models.ClientModels.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientPersonId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.EmployeeModels.Employee", b =>
                {
                    b.HasOne("EcommerceBackend.Core.Domain.Models.EmployeeModels.EmployeeAccount", "EmployeeAccount")
                        .WithOne("Employee")
                        .HasForeignKey("EcommerceBackend.Core.Domain.Models.EmployeeModels.Employee", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceBackend.Core.Domain.Models.ClientXEmployeeModels.Person", "Person")
                        .WithOne("Employee")
                        .HasForeignKey("EcommerceBackend.Core.Domain.Models.EmployeeModels.Employee", "PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmployeeAccount");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.EmployeeModels.EmployeeAccount", b =>
                {
                    b.HasOne("EcommerceBackend.Core.Domain.Models.EmployeeModels.EmployeeAccountType", "EmployeeAccountType")
                        .WithMany("EmployeeAccounts")
                        .HasForeignKey("AccountTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceBackend.Core.Domain.Models.ClientXEmployeeModels.Token", "token")
                        .WithOne("EmployeeAccount")
                        .HasForeignKey("EcommerceBackend.Core.Domain.Models.EmployeeModels.EmployeeAccount", "TokenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeAccountType");

                    b.Navigation("token");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.OrderModels.Order", b =>
                {
                    b.HasOne("EcommerceBackend.Core.Domain.Models.ClientModels.Client", "client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("client");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.OrderModels.OrderItem", b =>
                {
                    b.HasOne("EcommerceBackend.Core.Domain.Models.OrderModels.Order", "order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceBackend.Core.Domain.Models.ProductModels.Product", "product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("order");

                    b.Navigation("product");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.Product", b =>
                {
                    b.HasOne("EcommerceBackend.Core.Domain.Models.ProductModels.Types", "Types")
                        .WithMany("Products")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Types");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.ProductMainImages", b =>
                {
                    b.HasOne("EcommerceBackend.Core.Domain.Models.ProductModels.Product", "Product")
                        .WithMany("MainProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.ProductXColorsXSizes", b =>
                {
                    b.HasOne("EcommerceBackend.Core.Domain.Models.ProductModels.Colors", "ProductColors")
                        .WithMany("ProductXColorsXSizes")
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceBackend.Core.Domain.Models.ProductModels.ProductXSizes", "ProductXSizes")
                        .WithMany("ProductXColorsXSizes")
                        .HasForeignKey("ProductXSizesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductColors");

                    b.Navigation("ProductXSizes");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.ProductXColorsXSizesImages", b =>
                {
                    b.HasOne("EcommerceBackend.Core.Domain.Models.ProductModels.ProductXColorsXSizes", "ProductXColorsXSizes")
                        .WithMany("ProductXColorsXSizesImages")
                        .HasForeignKey("ProductXColorsXSizesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductXColorsXSizes");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.ProductXSizes", b =>
                {
                    b.HasOne("EcommerceBackend.Core.Domain.Models.ProductModels.Product", "Product")
                        .WithMany("ProductXSizes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcommerceBackend.Core.Domain.Models.ProductModels.Sizes", "Size")
                        .WithMany("ProductXSizes")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.BookModels.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.BookModels.Book", b =>
                {
                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.BookModels.BookType", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ClientModels.Client", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ClientModels.ClientAccount", b =>
                {
                    b.Navigation("Client");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ClientXEmployeeModels.Person", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ClientXEmployeeModels.Token", b =>
                {
                    b.Navigation("EmployeeAccount");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.EmployeeModels.EmployeeAccount", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.EmployeeModels.EmployeeAccountType", b =>
                {
                    b.Navigation("EmployeeAccounts");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.OrderModels.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.Colors", b =>
                {
                    b.Navigation("ProductXColorsXSizes");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("MainProductImages");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductXSizes");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.ProductXColorsXSizes", b =>
                {
                    b.Navigation("ProductXColorsXSizesImages");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.ProductXSizes", b =>
                {
                    b.Navigation("ProductXColorsXSizes");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.Sizes", b =>
                {
                    b.Navigation("ProductXSizes");
                });

            modelBuilder.Entity("EcommerceBackend.Core.Domain.Models.ProductModels.Types", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
